name: iOS und MacOS Build/Release

on:
  workflow_dispatch:
    inputs:
      blubb:
        description: 'Never Mind'
        required: false
        default: ''
  push:
    branches:
      - 'stable'
      - 'beta'
      - 'macos-stable'


jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: ['ios', 'macos']
    name: "Build ${{ matrix.platform }}"
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: ci-install-deps
        env:
          BLACKBOX_SECRET: ${{ secrets.BLACKBOX_SECRET_KEY }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: "./authpass/_tools/ci-install-deps.sh ios"
      - name: 'ci-release ${{ matrix.platform }}'
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: "./authpass/_tools/ci-release.sh ${{ matrix.platform }}"
